/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/core/Banner.vue')['default']
    CheckButton: typeof import('./src/components/CheckButton.vue')['default']
    Confirm: typeof import('./src/components/Confirm.vue')['default']
    Date: typeof import('./src/components/Date.vue')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    Fa6SolidXmark: typeof import('~icons/fa6-solid/xmark')['default']
    HeroiconsOutlineMenu: typeof import('~icons/heroicons-outline/menu')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    LanguageSwitcher: typeof import('./src/components/core/LanguageSwitcher.vue')['default']
    Layout: typeof import('./src/components/core/Layout.vue')['default']
    LikertScale: typeof import('./src/components/LikertScale.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Navbar: typeof import('./src/components/core/Navbar.vue')['default']
    PrimaryButton: typeof import('./src/components/PrimaryButton.vue')['default']
    Question: typeof import('./src/components/Question.vue')['default']
    RadioButtonGroup: typeof import('./src/components/RadioButtonGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./src/components/SecondaryButton.vue')['default']
    Spline: typeof import('./src/components/Spline.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
  }
}
